version: '3.4'

services:
  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    environment:
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings__DefaultConnection=Server=db;Database=SkiSchoolDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
      - "IdentityServer__Key__Type=Development"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure

  db:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      - "MSSQL_SA_PASSWORD=Your_password123"
      - "ACCEPT_EULA=Y"
      - "MSSQL_PID=Developer"